[[Product]]
= Product API


== 상품 목록 조회

=== GET /products
상품 목록을 JSON 형태로 돌려준다.

operation::get-products[snippets='http-request,http-response']

operation::get-products[snippets= 'response-fields']

&#160;

== 상품 단일 상세 조회

=== GET /product
상품에 대한 자세한 정보를 JSON 형태로 돌려준다.


operation::get-product[snippets='path-parameters']

&#160;

operation::get-product[snippets='http-request,http-response']

&#160;

operation::get-product[snippets= 'response-fields']

&#160;

== 상품 정보 등록

=== POST /product
상품을 등록하고, 등록된 정보를 JSON 형태로 돌려준다.

operation::create-product[snippets='request-body,request-fields']

&#160;

operation::create-product[snippets='http-request,http-response']

&#160;

operation::create-product[snippets= 'response-fields']

&#160;

== 상품 정보 수정

=== PATCH /product
상품을 수정하고, 수정된 정보를 JSON 형태로 돌려준다.

operation::update-product[snippets='path-parameters']

&#160;

operation::update-product[snippets='request-body,request-fields']

&#160;

operation::update-product[snippets='http-request,http-response']

&#160;

== 상품 정보 삭제

=== DELETE /product
상품을 삭제한다.


operation::delete-product[snippets='path-parameters']

&#160;

operation::delete-product[snippets='http-request,http-response']
